Repository jcornaz/kwik, pull requests merged in 2020-08, with the labels that each got.

#187 chore: Automate changelog generation
  .github/workflows/build.yml
  .versionrc.json
  CHANGELOG.md
  RELEASE.md
  example/build.gradle.kts
Labels: chore

#180 docs: Add a roadmap
  README.rst
  ROADMAP.md
Labels: documentation

#155 chore: Add dokka plugin
  build.gradle.kts
Labels: documentation

#181 feat: Add Duration/Instant/LocalTime generators
  generator/stdlib/src/jvmMain/kotlin/com/github/jcornaz/kwik/generator/stdlib/DateTime.kt
  generator/stdlib/src/jvmTest/kotlin/com/github/jcornaz/kwik/generator/stdlib/DateTimeGeneratorTest.kt
Labels: improvement

#190 ci: Fix publication job
  .github/workflows/publish.yml
Labels: chore

#189 chore(deps): Upgrade kotlin to 1.4
  .github/workflows/publish.yml
  .versionrc.json
  README.rst
  VERSION
  build.gradle.kts
  codecov.yml
  detekt-config.yml
  evaluator/src/commonTest/kotlin/com/github/jcornaz/kwik/evaluator/AbstractRunnerTest.kt
  evaluator/src/commonTest/kotlin/com/github/jcornaz/kwik/evaluator/CheckForAll1Test.kt
  evaluator/src/commonTest/kotlin/com/github/jcornaz/kwik/evaluator/CheckForAll2Test.kt
  evaluator/src/commonTest/kotlin/com/github/jcornaz/kwik/evaluator/CheckForAll3Test.kt
  evaluator/src/commonTest/kotlin/com/github/jcornaz/kwik/evaluator/CheckForAll4Test.kt
  evaluator/src/commonTest/kotlin/com/github/jcornaz/kwik/evaluator/ForAll1Test.kt
  evaluator/src/commonTest/kotlin/com/github/jcornaz/kwik/evaluator/ForAll2Test.kt
  evaluator/src/commonTest/kotlin/com/github/jcornaz/kwik/evaluator/ForAll3Test.kt
  evaluator/src/commonTest/kotlin/com/github/jcornaz/kwik/evaluator/ForAll4Test.kt
  evaluator/src/commonTest/kotlin/com/github/jcornaz/kwik/evaluator/ForAnyTest.kt
  fuzzer/api/src/commonMain/kotlin/com/github/jcornaz/kwik/fuzzer/api/FuzzerFactory.kt
  fuzzer/api/src/commonMain/kotlin/com/github/jcornaz/kwik/fuzzer/api/simplifier/Simplifier.kt
  fuzzer/api/src/commonMain/kotlin/com/github/jcornaz/kwik/fuzzer/api/simplifier/SimplifierFactory.kt
  fuzzer/api/src/commonMain/kotlin/com/github/jcornaz/kwik/fuzzer/api/simplifier/SimplifierOperators.kt
  fuzzer/api/src/commonTest/kotlin/com/github/jcornaz/kwik/fuzzer/api/EnsureAtLeastOneTest.kt
  fuzzer/api/src/commonTest/kotlin/com/github/jcornaz/kwik/fuzzer/api/FuzzerFilterTest.kt
  fuzzer/api/src/commonTest/kotlin/com/github/jcornaz/kwik/fuzzer/api/FuzzerPairTest.kt
  fuzzer/api/src/commonTest/kotlin/com/github/jcornaz/kwik/fuzzer/api/FuzzerTripleTest.kt
  fuzzer/api/src/commonTest/kotlin/com/github/jcornaz/kwik/fuzzer/api/GeneratorToFuzzerTest.kt
  fuzzer/api/src/commonTest/kotlin/com/github/jcornaz/kwik/fuzzer/api/simplifier/PairTest.kt
  fuzzer/api/src/commonTest/kotlin/com/github/jcornaz/kwik/fuzzer/api/simplifier/TripleTest.kt
  fuzzer/stdlib/src/commonTest/kotlin/com/github/jcornaz/kwik/fuzzer/stdlib/ArbitraryIntTest.kt
  fuzzer/stdlib/src/commonTest/kotlin/com/github/jcornaz/kwik/fuzzer/stdlib/simplifier/IntSimplifierTest.kt
  generator/api/src/commonMain/kotlin/com/github/jcornaz/kwik/generator/api/Generator.kt
  generator/api/src/commonMain/kotlin/com/github/jcornaz/kwik/generator/api/GeneratorOperators.kt
  generator/api/src/commonTest/kotlin/com/github/jcornaz/kwik/generator/api/AndThenTest.kt
  generator/api/src/commonTest/kotlin/com/github/jcornaz/kwik/generator/api/CombineTest.kt
  generator/api/src/commonTest/kotlin/com/github/jcornaz/kwik/generator/api/FilterTest.kt
  generator/api/src/commonTest/kotlin/com/github/jcornaz/kwik/generator/api/FrequencyGeneratorTest.kt
  generator/api/src/commonTest/kotlin/com/github/jcornaz/kwik/generator/api/MapTest.kt
  generator/api/src/commonTest/kotlin/com/github/jcornaz/kwik/generator/api/PlusOperatorTest.kt
  generator/api/src/commonTest/kotlin/com/github/jcornaz/kwik/generator/api/WithSampleTest.kt
  generator/stdlib/src/commonMain/kotlin/com/github/jcornaz/kwik/generator/stdlib/Collections.kt
  generator/stdlib/src/commonMain/kotlin/com/github/jcornaz/kwik/generator/stdlib/Defaults.kt
  generator/stdlib/src/commonMain/kotlin/com/github/jcornaz/kwik/generator/stdlib/Primitives.kt
  generator/stdlib/src/commonMain/kotlin/com/github/jcornaz/kwik/generator/stdlib/Sequences.kt
  generator/stdlib/src/commonMain/kotlin/com/github/jcornaz/kwik/generator/stdlib/Strings.kt
  generator/stdlib/src/commonTest/kotlin/com/github/jcornaz/kwik/generator/stdlib/CreateGeneratorTest.kt
  generator/stdlib/src/commonTest/kotlin/com/github/jcornaz/kwik/generator/stdlib/MapGeneratorTest.kt
  generator/stdlib/src/commonTest/kotlin/com/github/jcornaz/kwik/generator/stdlib/SequenceGeneratorTest.kt
  generator/stdlib/src/commonTest/kotlin/com/github/jcornaz/kwik/generator/stdlib/SetGeneratorTest.kt
  generator/stdlib/src/jvmMain/kotlin/com/github/jcornaz/kwik/generator/stdlib/DateTime.kt
  generator/stdlib/src/jvmMain/kotlin/com/github/jcornaz/kwik/generator/stdlib/UUIDs.kt
  settings.gradle.kts
Labels: chore

#197 docs: Recomands to use the fun interface to create a custom generator
  docs/write-tests.rst
  example/build.gradle.kts
  example/src/test/kotlin/com/github/jcornaz/kwik/example/PlusOperatorExample.kt
Labels: documentation

#198 chore: Remove deprecated members
  fuzzer/api/src/commonMain/kotlin/com/github/jcornaz/kwik/fuzzer/api/simplifier/SimplifierFactory.kt
  generator/api/src/commonMain/kotlin/com/github/jcornaz/kwik/generator/api/Generator.kt
  generator/api/src/commonMain/kotlin/com/github/jcornaz/kwik/generator/api/GeneratorOperators.kt
  generator/api/src/commonTest/kotlin/com/github/jcornaz/kwik/generator/api/WithSampleTest.kt
Labels: chore
